# Generated by Django 4.0 on 2021-12-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohoraextra',
            options={'verbose_name': 'Registro hora extra', 'verbose_name_plural': 'Registro horas extras'},
        ),
    ]
